# Generated by Django 6.0.2 on 2026-02-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('NAME', 'Name'), ('PHONE', 'Phone'), ('DONE', 'Done')], default='START', max_length=20),
        ),
    ]
